name: ensemble_sync
description: 합주 피드백 협업 플랫폼 EnsembleSync
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  web_socket_channel: ^2.4.0  # S#2 WebSocket 협업용 (미리 추가)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true